import type { ModelItem } from './types';
export type ModelSchemaItem = {
    key: string;
    value: string;
};
export type ModelSchemaField = {
    _gql?: string;
    _hidden?: boolean;
    _omit?: string[];
    _override?: boolean;
    required?: boolean;
    default?: any;
    select?: any;
    validate?: any;
    get?: any;
    set?: any;
    alias?: any;
    immutable?: any;
    transform?: any;
    lowercase?: boolean;
    uppercase?: boolean;
    trim?: any;
    match?: any;
    enum?: any;
    minLength?: any;
    maxLength?: any;
    populate?: any;
    index?: any;
    unique?: any;
    min?: any;
    max?: any;
    expires?: any;
    [k: string]: any;
};
export declare const toTypeDefs: (items: {
    key: string;
    value: string;
}[]) => string;
export declare const modelsToSchema: (models: ModelItem[]) => ModelSchemaItem[];
export declare const toSchema: (models: ModelItem[]) => string;
